# Generated by Django 4.2.1 on 2023-05-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_tags_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(default='Happy', max_length=20),
        ),
    ]
